Remove optimization for system-wide verifier
The virtualenv was taking a long time to create so I thought
it would be worth while, but it turns out the global pip installs
broke some stuff:

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cumulus.openstack.hpc.cam.ac.uk', port=5000): Max retries exceeded with url: /v3/auth/tokens (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))